export const GET_FIREBASE_COLLECTION = 'GET_FIREBASE_COLLECTION';
export const GET_FIREBASE_COLLECTION_SUCCESS = 'GET_FIREBASE_COLLECTION_SUCCESS';
export const GET_FIREBASE_COLLECTION_ERROR = 'GET_FIREBASE_COLLECTION_ERROR';
