export const GET_COLLECTION = 'GET_COLLECTION';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_SUCCESS';
export const GET_COLLECTION_ERROR = 'GET_COLLECTION_ERROR';

export const POST_ITEM = 'POST_ITEM'
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS'
export const POST_ITEM_ERROR = 'POST_ITEM_ERROR'

export const DELETE_ITEM = 'DELETE_ITEM'
export const DELETE_ITEM_SUCCESS = 'DELETE_ITEM_SUCCESS'
export const DELETE_ITEM_ERROR = 'DELETE_ITEM_ERROR'