export const OPEN_ADD_ITEM_MODAL = 'OPEN_ADD_ITEM_MODAL';
export const CLOSE_ADD_ITEM_MODAL = 'CLOSE_ADD_ITEM_MODAL';

export const INCREMENT_SCREEN_COUNTER = 'INCREMENT_SCREEN_COUNTER';
export const DECREMENT_SCREEN_COUNTER = 'DECREMENT_SCREEN_COUNTER';
